name: Sync to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: 'Thesis Main/phdthesis_YiGu.pdf'
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          # overwrite: 'true' # optional boolean